src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 40)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getFormatedDescription(): ?string
    {
        if (strlen($this->description) > 30){
            $str =  substr($this->description, 0, 30) . '...';
            return $str;
        }
        else{
            return $this->description;
        }
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ArticleFormType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleFormType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/post')]
class PostController extends AbstractController
{   

    /**
     * @param ArticleRepository $repository
     */
    private $repository;

     /**
     * @param EntityManagerInterface $em
     */
    private $em;

    public function __construct(ArticleRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    #[Route('/', name: 'post.index')]
    public function index(): Response
    {
        $articles = $this->repository->findAll();
        return $this->render('post/index.html.twig', compact('articles'));
    }

    #[Route('/add', name: 'post.add')]
    public function add(Request $request){
        $article = new Article;

        $form = $this->createForm(ArticleFormType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // ... perform some action, such as saving the task to the database
            $this->em->persist($article);
            $this->em->flush();

            return $this->redirectToRoute('post.index');
        }

        return $this->render('post/add.html.twig', [
            "article" => $article,
            'form' => $form->createView()
        ]);
    }

    #[Route('/show/{id}', name: 'post.show')]
    public function show(Article $article, Request $request){
        $form = $this->createForm(ArticleFormType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // ... perform some action, such as saving the task to the database
            $this->em->flush();

            return $this->redirectToRoute('post.index');
        }

        return $this->render('post/show.html.twig', [
            "article" => $article,
            'form' => $form->createView()
        ]);
    }

    #[Route('/delete/{id}', name: 'post.delete')]
    public function delete(Article $article){
            $this->em->remove($article);
            $this->em->flush();
            return $this->redirectToRoute('post.index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} {% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ path('post.index') }}">Crud avec Symfony</a>
            </div>
        </nav>

        {% block body %}{% endblock %} 
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/post/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add{% endblock %}

{% block body %}
<div class="container mt-4">
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary" type="submit">Sauvegarder</button>
{{ form_end(form) }}


<a class="btn btn-warning center mt-4" href="{{ path('post.index') }}">Retour</a>

</div>

{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <div class="container g-3 mt-4">
        <a href="{{ path('post.add') }}" class="btn btn-success"> + Ajouter</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Title</td>
                    <td>Description</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                <tr>
                    <td>{{ article.id }}</td>
                    <td>{{ article.title }}</td>
                    <td>{{ article.formatedDescription }}</td>
                    <td><a href="{{ path('post.show', {id: article.id}) }}" class="btn btn-primary m-1">Voir</a><a href="{{ path('post.delete', {id: article.id}) }}" class="btn btn-danger m-1">Supp</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update{% endblock %}

{% block body %}
<div class="container mt-4">
{{ form_start(form) }}
<div class="row">
    <div class="mt-4 col-md-12">{{ form_row(form.title) }}</div>
</div>
<div class="row">
    <div class="mt-4 col-md-12">{{ form_row(form.description) }}</div>
</div>
{{ form_widget(form) }}
<button class="btn btn-primary" type="submit">Sauvegarder</button>
{{ form_end(form) }}


<a class="btn btn-warning center mt-4" href="{{ path('post.index') }}">Retour</a>
</div>
{% endblock %}